### ISSUE TITLE
Integrate seamlessly with GPT Index (aka llamaindex)

### ISSUE THREAD

**Issue by hotkartoffel** [different-ai/embedbase#13]

**Comment by louis030195** [comment]
Seems there is an ongoing PR for Pinecone https://github.com/jerryjliu/gpt_index/pull/508
Might wait they merge to avoid pain with api changes
(or use weaviate, or smthing else)

**Comment by louis030195** [comment]
More context: https://github.com/jerryjliu/gpt_index/issues/271
