### ISSUE TITLE
Support for local databases

### ISSUE THREAD

**Issue by umaar** [different-ai/embedbase#18]
Great project. Would be nice to get support for a local DB, without having to rely on a third party.  Maybe a local PostgreSQL or local SQLite?

**Comment by louis030195** [comment]
> Great project. Would be nice to get support for a local DB, without having to rely on a third party. Maybe a local PostgreSQL or local SQLite?

@umaar  Interesting, could you elaborate on the use case for this, please 😄 ?

**Comment by hotkartoffel** [comment]
>  Great project. Would be nice to get support for a local DB, without having to rely on a third party. Maybe a local PostgreSQL or local SQLite?

I think that makes ton of sense. Eventually I'd even want a fully local deployment!

**Comment by umaar** [comment]
For example with pinecone, supabase etc. they're great but it's easy to quickly eat into your free tier which is tricky when doing hobby projects. Being able to use local databases means things can be set up very cheaply, or even free where the only costs are from OpenAI. My personal use case is ingesting some content I've written, being able to do semantic searching over my own content!

Thank you for this excellent project!

**Comment by louis030195** [comment]
@umaar interesting... There is a hosted version which is free, you can try at https://app.embedbase.xyz. It's useful to try out Embedbase, then you can self-host later if you want! 😃

**Comment by umaar** [comment]
Oh no, what I mean is the supabase portion. Right now, embedbase relies on supabase I believe? This GitHub issue to suggest not tying embedbase to supabase, but rather, allowing embedbase to work with other vector DBs. In fact, I just noticed this on the home page!

<img width="275" alt="image" src="https://user-images.githubusercontent.com/381495/225763422-5b1e629e-9779-464f-b66b-4d252ba7a176.png">

So i think that was the plan anyway?

**Comment by louis030195** [comment]
I could add a local db with FAISS eventually, should be done in ~20 minutes I have done this in the past here https://github.com/langa-me/langame-worker/blob/27bf899d485948c9635a76b8f91deb3c19e2d46d/langame/conversation_starters.py#L121

**Comment by umaar** [comment]
Thank you!
