### ISSUE TITLE
How to use with local embedbase deployment?

### ISSUE THREAD

**Issue by vadi2** [different-ai/embedbase#31]
https://docs.embedbase.xyz/tutorials/nextra-qa-docs is only setup for a cloudhosted embedbase - is there a way to get this to run with a local deployment?

**Comment by louis030195** [comment]
@vadi2 yes :)

You can use a local postgres for example

First, run Docker, then:
```bash
docker run -d --name pgvector -p 8080:8080 -p 5432:5432 \
    -e POSTGRES_DB=embedbase -e POSTGRES_PASSWORD=localdb \
    -v data:/var/lib/postgresql/data ankane/pgvector
```

This will start a Docker container with an image that can handle vector data type and semantic search queries

You can then use either OpenAI to create embeddings like so:

```py
# main.py
import os
from embedbase import get_app
from embedbase.database.postgres_db import Postgres
from embedbase.embedding.openai import OpenAI
import uvicorn
 
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
 
app = (
    get_app()
    .use_embedder(OpenAI(OPENAI_API_KEY))
    .use_db(Postgres())
    .run()
)
 
if __name__ == "__main__":
    uvicorn.run("main:app", reload=True)
```

Make sure to install the dependencies `pip install embedbase uvicorn`, then you can start Embedbase:

```bash
python3 main.py
```

Make sure to replace references to "https://embedbase-hosted-usx5gpslaq-uc.a.run.app/v1/documentation" to "http://localhost:8000/v1/documentation" in your javascript/ts code.
We recommend using the [SDK](https://docs.embedbase.xyz/sdk), although this tutorial does not use the SDK yet, we will update it ASAP.

You can also run a local Embedbase with a custom "embedder" such as sentence transformer as explained [here](https://docs.embedbase.xyz/examples/implement-a-local-first-embedbase) if you want to keep everything local.

Please let me know if that solve your issue

**Comment by louis030195** [comment]
If you don't want to use Docker, you can also go with in memory database:

```py
import uvicorn
from embedbase import get_app

from embedbase.database.memory_db import MemoryDatabase
from embedbase.embedding.openai import OpenAI
 
app = (
    get_app()
    .use_embedder(OpenAI("<your key>"))
    .use_db(MemoryDatabase())
).run()

if __name__ == "__main__":
    uvicorn.run("main:app")
```

**Comment by louis030195** [comment]
@vadi2 feel free to reopen the issue with if you have any other problems 😃
