### ISSUE TITLE
async function call not working (uvicorn, fastapi)

### ISSUE THREAD

**Issue by ccomkhj** [different-ai/embedbase#71]
## 🐛 Bug Report

async function call not working (uvicorn, fastapi)

### Code sample

```
from embedbase_client.client import EmbedbaseClient
import yaml
from fastapi import FastAPI

with open("credential/embedbase.yaml", "r") as f:
    API = yaml.safe_load(f)
embedbase_key = API['EMBEDBASE_KEY']
embedbase_url = API['EMBEDBASE_URL']


app = FastAPI()


@app.get("/")
async def root():
    client = EmbedbaseClient(embedbase_url, embedbase_key)

    client.dataset('basil_greenhouse').search(
        'how to grow basil?', limit=5)
    return {"message": "Hello World"}
```
```
uvicorn bug_test:app
```

### Environment

* OS: Linux
* Python version, get it with: 3.8.16

### Screenshots

```
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

## 📈 Expected behavior

Return list of datasets

## 📎 Additional context

Using FastAPI

**Comment by louis030195** [comment]
@ccomkhj thanks! I had some issues also running sync client in async context, I'll try to investigate this, in the meantime prefer using the async client in async context:

```py
from embedbase_client.client import EmbedbaseAsyncClient
import yaml
from fastapi import FastAPI

with open("credential/embedbase.yaml", "r") as f:
    API = yaml.safe_load(f)
embedbase_key = API['EMBEDBASE_KEY']
embedbase_url = API['EMBEDBASE_URL']


app = FastAPI()


@app.get("/")
async def root():
    client = EmbedbaseAsyncClient(embedbase_url, embedbase_key)

    client.dataset('basil_greenhouse').search(
        'how to grow basil?', limit=5)
    return {"message": "Hello World"}
```

Please let me know if it solves your issue :)

**Comment by ccomkhj** [comment]
thanks for the quick response! it works! 👍

**Comment by louis030195** [comment]
@ccomkhj 

Hey 👋

You need to use `await` otherwise it does not get the value, eg:

```py
async def foo()
  return "bar"

print(foo())
# coroutine

print(await foo())
# bar
```

So in your context:

```py
results_recipe = await client.dataset(recipe_id).search(
      question, limit=6
  )  
results_farm = await client.dataset(farm_id).search(
      question, limit=1
  )  
results = results_recipe + results_farm
```

An optimization allowed by async would be to run requests in parallel:

```py
[results_recipe, results_farm] = await asyncio.gather(
  *[
    client.dataset(recipe_id).search(
      question, limit=6
    ) ,
    client.dataset(farm_id).search(
      question, limit=1
    )
  ]
)
# ...
```

This way the code would be twice faster.

Would you use a simpler API, like:

```py
results = client.dataset(recipe_id, farm_id).search(question, limit=6)
```

? I guess here it does not make sense because you want a limit of `6`, and `1`?

**Comment by ccomkhj** [comment]
Thank you for the ready-to run example. @louis030195 
It works super fast!

It would be so helpful in my use-case
```
results = await client.dataset(recipe_id, farm_id, user_id, locaton_id).search(question, max_token=3000, ratio=[.7, .1, .1, .1)
```
max_token of 2100, 300, 300, 300 are applied to each dataset.

**Comment by hotkartoffel** [comment]
@ccomkhj 


> ```
> results_recipe = client.dataset(recipe_id).search(
>       question, limit=6
>   )  
> results_farm = client.dataset(farm_id).search(
>       question, limit=1
>   )  


Curious, why you're using multiple datasets? Is there a reason you didn't put everything in a single dataset?

**Comment by ccomkhj** [comment]
Two reasons.
1. Each dataset has a different purpose (I.e. one is about person, one is about company, one is about culture, and so on), so easy to manage diverse datasets.
2. Guarantee to include something dataset (not ranked by only similarity)

**Comment by hotkartoffel** [comment]
@ccomkhj I see, makes sense!
