### ISSUE TITLE
Implement Weaviate

### ISSUE THREAD

**Issue by louis030195** [different-ai/embedbase#8]
weaviate.io

**Comment by hotkartoffel** [comment]
Would be really up to integrate it:
1. It's open-source
2. Their three modes of search (see screenshot) are fabulous and I think Embedbase should integrate all three of them eventually

<img width="1015" alt="Screenshot 2023-02-17 at 11 07 30 PM" src="https://user-images.githubusercontent.com/11430621/219803048-3c5b6533-bd90-4070-9f6d-3e8de3db6507.png">

**Comment by louis030195** [comment]
@hotkartoffel feel free to
